# Site settings
author: Agi
title: Agi's blog
header-img: img/home-bg.png
email: a.letkiewicz@gmail.com
copyright_name: Agi
description: > # this means to ignore newlines until "baseurl:"
  A software engineering bootcamp journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  agiletkiewicz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
